# -*- coding: utf-8 -*-
"""Assignment 22 nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S29l33ucG1EZ9RqaehSt7Pq-Z3raOY1r
"""

#  Semantic Similarity

import nltk
from nltk.corpus import wordnet as wn

# Download WordNet (run once)
nltk.download('wordnet')

def similarity(word1, word2):
    syn1 = wn.synsets(word1)
    syn2 = wn.synsets(word2)

    if syn1 and syn2:
        return syn1[0].wup_similarity(syn2[0])
    return None

pairs = [
    ("car", "automobile"),
    ("happy", "joyful"),
    ("big", "large"),
    ("teacher", "professor"),
    ("dog", "animal")
]

for w1, w2 in pairs:
    print(f"{w1} - {w2} => {similarity(w1, w2)}")

