# -*- coding: utf-8 -*-
"""assignment 27 opencv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-gPy2pIsFsDrF-QZ8IXA8BHH_KJZz6k
"""

# Image Filters using OpenCV (Google Colab)

import cv2
import matplotlib.pyplot as plt
from sklearn.datasets import load_sample_image

# Load inbuilt image
image = load_sample_image("china.jpg")

# Convert RGB to BGR for OpenCV processing
image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

# Convert to grayscale
gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

# Blur image
blur = cv2.GaussianBlur(image_bgr, (5, 5), 0)

# Edge detection
edges = cv2.Canny(image_bgr, 100, 200)

# Convert back to RGB for display
image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
blur_rgb = cv2.cvtColor(blur, cv2.COLOR_BGR2RGB)

# Display using matplotlib
plt.figure(figsize=(10,8))

plt.subplot(2,2,1)
plt.imshow(image_rgb)
plt.title("Original")
plt.axis('off')

plt.subplot(2,2,2)
plt.imshow(gray, cmap='gray')
plt.title("Grayscale")
plt.axis('off')

plt.subplot(2,2,3)
plt.imshow(blur_rgb)
plt.title("Blurred")
plt.axis('off')

plt.subplot(2,2,4)
plt.imshow(edges, cmap='gray')
plt.title("Edges")
plt.axis('off')

plt.show()

