# -*- coding: utf-8 -*-
"""Assignment 20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLoW3bOS7FYhhWIbqAzTFejmbDreLqYg
"""

#Word Importance using TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "AI is transforming the world",
    "Machine learning is a part of AI",
    "Deep learning is a subset of machine learning",
    "AI and ML are widely used in industry",
    "Learning algorithms improve performance"
]

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

features = vectorizer.get_feature_names_out()

for i, row in enumerate(tfidf_matrix.toarray()):
    print(f"\nDocument {i+1}:")
    top_indices = row.argsort()[-3:]
    for index in top_indices:
        print(features[index])

