# -*- coding: utf-8 -*-
"""assignment 28 opencv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ZPddKf4aPnffipdfImcYEQF9ZCwHVcD
"""

# Assignment 4: Face Detection (100% Working - Colab)

!pip install opencv-python matplotlib

import cv2
import matplotlib.pyplot as plt
import urllib.request
import numpy as np

# 🔥 Download a real face image (guaranteed detection)
url = "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/lena.jpg"
urllib.request.urlretrieve(url, "face.jpg")

# Load image
image = cv2.imread("face.jpg")

# Convert to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Load Haar Cascade
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
)

# Detect faces (reliable parameters)
faces = face_cascade.detectMultiScale(
    gray,
    scaleFactor=1.3,
    minNeighbors=5
)

# Draw rectangle
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x,y), (x+w,y+h), (255,0,0), 2)

# Convert BGR → RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Show image
plt.imshow(image_rgb)
plt.title("Face Detection (Working Output)")
plt.axis('off')
plt.show()

print("Number of faces detected:", len(faces))

'''5 Uses of Face/Object Detection
1.Face Recognition for Attendance
   Automatically marks attendance using camera
   Used in schools, colleges, offices
2.Self-Driving Cars
   Detects pedestrians, vehicles, traffic signals
   Helps in safe navigation
3.Security & Surveillance
   Detects suspicious activity in public places
   Used in airports, malls, banks
4.Medical Imaging
   Detects tumors or abnormalities in X-rays/MRI
   Helps doctors in diagnosis
5.Retail Analytics
   Tracks customer movement and behavior
   Helps improve store layout and sales'''