# -*- coding: utf-8 -*-
"""assignment 24 nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vsuvCnbDiWq9iCB7mVCWqDms6Iq-NjW
"""

#  Prompt Engineering

data = {
    "Resume": {
        "Weak": "Make resume",
        "Strong": "Create a professional resume for a B.Tech student skilled in Python, SQL, and Machine Learning including projects."
    },
    "Business Idea": {
        "Weak": "Give business idea",
        "Strong": "Suggest an AI-based startup idea for students with low investment and high growth potential."
    },
    "Study Plan": {
        "Weak": "Give study plan",
        "Strong": "Create a 2-month SSC CPO study plan covering reasoning, math, and GK with daily schedule."
    }
}

for category, prompts in data.items():
    print(f"\n{category}")
    print("Weak Prompt :", prompts["Weak"])
    print("Strong Prompt:", prompts["Strong"])

